version: '3'
services :
  web :
    image : ocsinventory/ocsinventory-docker-image:latest
    container_name : ocsinventory-server
    environment :
      OCS_DBNAME : ocsweb
      OCS_DBSERVER_READ : ocsinventory-db
      OCS_DBSERVER_WRITE : ocsinventory-db
      OCS_DBUSER : ocs
      OCS_DBPASS : ocs
    volumes :
      - ocssrv:/usr/share/ocsinventory-reports/
      - ocssrv:/etc/ocsinventory-reports/
      - ocssrv:/var/lib/ocsinventory-reports/
    links :
      - db
    ports :
      - 80:80
      - 443:443

  db :
    image : mysql:5.7
    container_name : ocsinventory-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD : mdp
      MYSQL_USER : ocs
      MYSQL_PASSWORD : ocs
      MYSQL_DATABASE : ocsweb
    volumes :
      - ./sql/:/docker-entrypoint-initdb.d/
      - ocsdata:/var/lib/mysql
    ports :
      - 3306:3306

volumes:
  ocsdata:
    driver: local
  ocssrv:
    driver: local
